# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'       # for Fira Code and a patched font for vim/neovim
tap 'homebrew/cask-versions'    # for alternate versions of Casks
tap 'yqrashawn/goku'            # For Goku

# Productivity and automation (see: https://tighten.com/blog/how-to-train-your-keyboard/)
cask 'karabiner-elements'   # Remap keys and shortcuts at the kernel level
cask 'hammerspoon'          # Take Karabiner's shortcuts and make the magic happen
# brew 'yqrashawn/goku/goku'  # Manage Karabiner configs with ease

# Fonts
cask 'font-fira-code'